version: '3.8'
services:
  movies:
    image: gsai1819/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
    volumes:
      - "movies"
  train:
    image: gsai1819/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - "train"
  dth:
    image: gsai1819/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - "dth"
  recharge:
    image: gsai1829/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
    volumes:
      - "recharge"

